### ISSUE TITLE
@Mateusbertolini to-do list

### ISSUE THREAD

**Issue by pedroaf0** [Mateusbertolini/proof_of_concept#2]
- [x] Trocar o seletor de raça de radio para select
![aaa](https://github.com/Mateusbertolini/proof_of_concept/assets/54213349/54e2b84a-73f1-48ab-9f3e-435da036b28a)
- [x] Trocar as checkbox de Condição sistêmica/Necessidade especial por multselect [w3schools.com/TAGS/att_select_multiple.asp](https://www.w3schools.com/TAGS/att_select_multiple.asp)
![sss](https://github.com/Mateusbertolini/proof_of_concept/assets/54213349/21843ffb-c312-4cfb-82b0-dd52f987bf4b)

_Essas alterações tornaram mais fácil a integração com o servidor_

**Comment by Mateusbertolini** [comment]
Feito!
