### ISSUE TITLE
To do list (ajustes e próximos passos):

### ISSUE THREAD

**Issue by Mateusbertolini** [Mateusbertolini/proof_of_concept#22]
- [x] Consulta > Meus pacientes => BUSCAR A LISTAGEM DE PACIENTES REGISTRADOS NA VARIÁVEL 'vinculoPacientes'
- [x] Consulta > Paciente => Está dando erro 404 quando se clica no nome do paciente
- [x] Cadastro > Registrar demanda => Add linhas na tabela junto com a função de salvar no banco
- [ ]  variáveis 'demandaAreaSaude', 'demandaEspecialidade' e 'demandaEspecifica' devem popular a 'table2' da página vincular-2.html;
- [x] Front-end vincular-2.html com scripts para funções
- [x] Front-end desvincular-2.html com scripts para funções
- [ ] variável 'demandaComplexidade' deve/pode filtrar os dados da 'table2'
- [x] Criar perfil para "Enfermagem"

**Comment by pedroaf0** [comment]
### Cadastro sem CPF como documento obrigatório
- [ ] Alterar API para permitir a cunsulta por id
- [ ] Alterar busca para enviar o id no lugar do atual CPF
- [ ] Aterar pagina de visualização para consultar por id
- [ ] Alterar pagina de edição para consultar por id
---
### Meus pacientes
- [ ] Criar tabela alunos (?)
- [ ] Adicionar Alunos com vinculo na tabela "pacientes"
- [ ] Atualizar rota ```pacientes/consultar/``` que recebe a matricula do do aluno
- [ ] Atualizar API.js
- [ ] Integrar com pagina meus pacientes
---
###  variável "Complexidade' pode filtrar os dados da tabela "demandas"
- [ ] Atualizar ```encaminhamentos/consultar``` para receber um filtro

**Comment by pedroaf0** [comment]
- [x] criar arquivo js dos indexs, com corretor de links 
- [x] adicionar link do iframe via url

**Comment by pedroaf0** [comment]
- [x] criar tabela usuários cobalto para alunos, professores, servidores 

Colunas: tipo de usuário, matrícula, nome, pacientes

**Comment by pedroaf0** [comment]
@Mateusbertolini & @pedroaf0 
- [x] Criar mais dados fictícios para alunos com nomes comuns
- [x] Criar mais dados fictícios para pacientes com nomes comuns 
- [x] Criar mais dados fictícios para demandas com diferentes complexidades, especialidade e texto coerente
- [x] Criar disciplinas e adicionar os novos alunos 
Da pra usar o chatgtp mas pedir para ele usar nomes comuns em português

**Comment by pedroaf0** [comment]
@pedroaf0 
- [ ] Finalizar vincular
### Upload de arquivos
- [ ] Criar tabela arquivos com CPF, nome, link e data
- [ ] Criar rota upload
- [ ] criar rota download

@Mateusbertolini 
- [ ] Criar arquivos fictícios de exames e radiografias
